hover_control_node:
  ros__parameters:
    gravity: 9.81 # m/s²
    mass: 3.646 # kg
    I: [0.04092, 0.04019, 0.06921, 3.646, 3.464, 3.464]  # kg*m²

path_following_node:
  ros__parameters:
    gravity: 9.81 # m/s²
    mass: 3.646  # kg
    I: [0.04092, 0.04019, 0.06921, 3.646, 3.464, 3.464]  # kg*m²